<?php

/**
* Implements hook_block_info().
*/
function portfolio_overview_block_info() {
	$blocks['overview'] = array(
	'info' => 'Portfolio Overview',
	);
	return $blocks;
}

/**
* Implements hook_block_view().
*/

function portfolio_overview_blockview() {
	$block['subject'] = 'Portfolio at a Glance';
	$block['content'] = "Hello World";
	return $block;
}

function portfolio_overview_output() {
	$blog_count = db_query("SELECT COUNT(nid) 
				FROM  `node` 
				WHERE TYPE =  'blog_post'"
	)->fetchColumn();
	$badge_count = db_query("SELECT COUNT(nid) 
				FROM  `node` 
				WHERE TYPE =  'badge'"
	)->fetchColumn();
	$project_count = db_query("SELECT COUNT(nid) 
				FROM  `node` 
				WHERE TYPE =  'project'"
	)->fetchColumn();
	$skills_count = db_query("SELECT COUNT(tid) 
				FROM  `taxonomy_term_data` 
				WHERE vid = 1"
	)->fetchColumn();
	$output = '<h3>' . $blog_count . 'blog posts written</h3>';
	$output .= '<h3>3 badges earned</h3>';
	$output .= '<h3>4 skills in progress</h3>';
	$output .= '<h3>2 projects to show off</h3>';
	return $output;
}